cc_dashboard_index:
    pattern: /{_locale}/dashboard
    defaults: { _controller: CCDNComponentDashboardBundle:Dashboard:index, _locale: en }

cc_dashboard_show:
    pattern: /{_locale}/dashboard/{category}
    defaults: { _controller: CCDNComponentDashboardBundle:Dashboard:show, _locale: en }


