ccdn_component_dashboard_index:
    pattern: /{_locale}/dashboard
    defaults: { _controller: CCDNComponentDashboardBundle:Dashboard:index, _locale: en }

ccdn_component_dashboard_show:
    pattern: /{_locale}/dashboard/{pageName}
    defaults: { _controller: CCDNComponentDashboardBundle:Dashboard:show, _locale: en }
