parameters:

    ccdn_component_dashboard.registry.class:         CCDNComponent\DashboardBundle\Component\Integrator\Registry\DashboardRegistry

    ccdn_component_dashboard.integrator_chain.class: CCDNComponent\DashboardBundle\Component\Integrator\Chain\IntegratorChain

    ccdn_component_dashboard.component.menu_builder.menu.class: CCDNComponent\DashboardBundle\Component\MenuBuilder\Menu

services:

    #
    # Dashboard Components.
    #
    ccdn_component_dashboard.registry:
        class: %ccdn_component_dashboard.registry.class%
        arguments: [@service_container]

    #
    # Dashboard Integrator.
    #
    ccdn_component_dashboard.integrator_chain:
        class: %ccdn_component_dashboard.integrator_chain.class%

    #
    # Menu Builder.
    #
    ccdn_component_dashboard.component.menu_builder.menu:
        class: %ccdn_component_dashboard.component.menu_builder.menu.class%
        tags:
            - { name: ccdn_component_menu.menu_builder }
    