parameters:

    # Service Parameters defined in app/config
    ccdn_component_dashboard.registry.class:         CCDNComponent\DashboardBundle\Component\Integrator\Registry\DashboardRegistry

    ccdn_component_dashboard.integrator_chain.class: CCDNComponent\DashboardBundle\Component\Integrator\Chain\IntegratorChain
    ccdn_component_dashboard.component.integrator.model.builder.class: CCDNComponent\DashboardBundle\Component\Integrator\Model\Builder

    #ccdn_component_dashboard.component.integrator.registry.class
    #ccdn_component_dashboard.component.integrator.chain.class
services:

    #
    # Dashboard Components.
    #
    ccdn_component_dashboard.registry:
        class: %ccdn_component_dashboard.registry.class%
        arguments:
            - @ccdn_component_dashboard.integrator_chain
            - @ccdn_component_dashboard.component.integrator.model.builder

    #
    # Dashboard Integrator.
    #
    ccdn_component_dashboard.integrator_chain:
        class: %ccdn_component_dashboard.integrator_chain.class%

    ccdn_component_dashboard.component.integrator.model.builder:
        class: %ccdn_component_dashboard.component.integrator.model.builder.class%
        arguments:
            - @security.context
            - @router
            - @translator
